### ISSUE TITLE
can i get charts on the "ground truth" results with xomo and pom?  

### ISSUE THREAD

**Issue by timm** [ai-se/XTREES#3]
can i get charts on the "ground truth" results with xomo and pom? need that for a grant i am writing

**Comment by rahlk** [comment]
See [https://github.com/ai-se/Transfer-Learning/issues/31](https://github.com/ai-se/Transfer-Learning/issues/31)

**Comment by rahlk** [comment]
+ In some cases, the improvement doesnt seem appreciable, the before/after ratio is perhaps not the best measure, given that we aim to make the least possible change. How about a Cliffs Delta score? Or, something else only for the ground truth.
+ In some cases, all treatments are ranked the same. This is probably due to the number of reps (which is 10 for the above results). Taking into account the variance in some cases, I think we need more reps.
