### ISSUE TITLE
more jureczko clarification

### ISSUE THREAD

**Issue by llayman** [ai-se/XTREES#39]
Jureczko data set: I read somewhere that defects are based on test cases? Where did the test cases come from? If they’re from the open source project, that’s a pretty terrible project for leaving known defects in their system if their own test cases found them. More detail on defects counts from Jureczko needed.

**Comment by rahlk** [comment]
@timm Fixed: (Jureczko uses a post release bug tracking system). 

**Modified paragraph (Section 3. Test Data):**
   The Jurecko data records number of known defects for each class using a post-release bug tracking system. The classes are described in terms of
  nearly two dozen metrics such as number of children, lines of code, etc. For details on the Jurecko data, see  \fig{ck} and \fig{jd}. 
 All the planning methods of this paper reflect on the numeric value of the raw defect counts. The predictor considers defects to be a discrete class data set,where defects are \textit{\texttt{TRUE}} if the numeric defect count is greater than zero and \textit{\texttt{FALSE}} otherwise.
